### ISSUE TITLE
Qukey only works with primary layer (If you LockLayer it stops functioning)

### ISSUE THREAD

**Issue by nevd** [keyboardio/Kaleidoscope-Qukeys#52]
I have two base layers for OSX and Windows. (Each utilises the same pair of extra layers)

I use a LockLayer to switch between layers.

When I invoke the alternate base layer the qukey does not fire.

Is there a way to specify the Qukey to be active on more than the primary layer?

**Comment by gedankenexperimenter** [comment]
Can you share your whole configuration? I can guess what you need, but it would be easier to see the actual Qukey definitions.

**Comment by nevd** [comment]
Sure https://github.com/nevd/keyboardio/blob/master/nevd.ino

I realised my first issue raised (and now closed) was exactly the same as the 2nd. I made the pgup a qukey for control and when i want to use control + arrows i could never use the qukey. Because I was in a different layer.

When I had to give up on using HostOS to remap a few keys I went down the road of separate layers for OS and then because I need to switch between them I found the qukey never worked in my Windows layer.

**Comment by gedankenexperimenter** [comment]
Thanks for sharing your sketch. The qukey doesn't work because it's only defined in layer `NEVD_OSX`. The first argument in the Qukey definition is the layer number; instead of this:
```
kaleidoscope::Qukey(0,2,0,Key_LeftControl))
```
…it would be clearer to write this:
```
kaleidoscope::Qukey(NEVD_OSX,2,0,Key_LeftControl))
```
You've got a few options for getting the behaviour you want. You could define another Qukey on your `NEVD_WIN` layer, or you could drop the full Qukey definition and use the DualUse macro in the keymap: `CTL_T(PageUp)` instead of `Key_PageUp` anywhere you want it. The easiest solution in this specific case, though, is to simply change that key to transparent (`___` instead of `Key_PageUp` on the `NEVD_WIN` layer).

**Comment by nevd** [comment]
Okay that makes total sense and I really should have re-read the documentation myself to figure it out. Apologies!

I think the best course of action is to let it fall through, as that is the behavior I want. I will use the layer name in the qukey as well so I will remember how it works!
